name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test
      - name: Build the main app
        run: flutter build apk -t lib/main.dart  
      
      - name: Install Widgetbook CLI
        run: dart pub global activate widgetbook_cli

      - name: Build Widgetbook
        run: |
          flutter pub get
          dart run build_runner build -d
          flutter build web -t lib/widgetbook.dart  # Specify Widgetbook entry point here

      - name: Push Widgetbook Build
        run: widgetbook cloud build push --api-key d203462773aa021c53ba826b9a51e8355c87c9e699eee53ad13b6289549b7801

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-build-artifact
          path: build/app/outputs/apk/release/app-release.apk  #
