name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Specify Java version 17
          distribution: 'temurin'  # Use Temurin JDK distribution

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'  # Specify the Flutter version you need

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build the app
        run: flutter build apk  # Change this to your desired build command
      - name: Run WidgetBook
        run: flutter run -d web-server -t lib/widgetbook.dart


      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-build-artifact
          path: build/app/outputs/apk/release/app-release.apk  # Adjust the path as needed
