name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Install dependencies
        run: flutter pub get
      
      - name: Get dependencies for widgetbook_workspace
        run: |
          cd widgetbook_workspace  # Navigate to widgetbook_workspace directory if it's local
          flutter pub get  # Install dependencies

      - name: Run build runner for Widgetbook
        run: dart run build_runner build

      - name: Run tests
        run: flutter test
      
      - name: Build the main app
        run: flutter build apk -t lib/main.dart

      - name: Install Widgetbook CLI
        run: dart pub global activate widgetbook_cli

      - name: Build Widgetbook
        run: |
          flutter pub get
          dart run build_runner build
          flutter build web -t widgetbook/lib/main.dart  # Adjusted to the root 'widgetbook' folder

      - name: Push Widgetbook Build
        run: widgetbook cloud build push --api-key c4ccb2b7747e7c298942dfa275c220f038c2b283b01d0f4a364c897e1fc1bdaf

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-build-artifact
          path: build/app/outputs/apk/release/app-release.apk
